- lib/decorators.ts
- tests/index-test.ts
Decorators could be used without parenthesis and in lowercase.
> refactor: ease of use of decorators

- tests/eager1.ts
- tests/eager2.ts
- tests/index-test.ts
> test: add test for eager dependencies

- README.md
- lib/component.ts
- lib/decorators.ts
- lib/external.ts
- lib/factory.ts
- lib/initialize.ts
- lib/inject.ts
- package-lock.json
- package.json
- tests/index-test.ts
For better debugging and understanability of injection one could set the
DEBUG variable to 'tsdi' now
> feat: add debug logging

- .editorconfig
- lib/external.ts
To work around older browsers and strict mode issues we need to filter
some more properties for external components
> fix: access to restricted properties

- .editorconfig
- lib/tsdi.ts
- tests/mock-test.ts
Add automocking of dependencies for easier testing.
> feat: add automock feature

- README.md
- lib/destroy.ts
- lib/tsdi.ts
- tests/index-test.ts
Add decorator and lifecycle callback for destroy state.
> feat: add destroy hook

- lib/tsdi.ts
- package-lock.json
- tests/index-test.ts
If a scope is left all components of other scopes should be kept alive.
> fix: do not destroy components of other scopes

- docs/api-tsdi.md
- docs/externals.md
- docs/features.md
- lib/external.ts
- lib/tsdi.ts
- tests/external.test.ts
- website/i18n/en.json
- website/sidebars.json
- website/siteConfig.js
- website/versioned_docs/version-0.20.0/features.md
This allows custom external container resolutions.
For example per user or per request containers.
Closes #268
> feat: add container resolution strategy for externals

- lib/tsdi.ts
BREAKING CHANGE: update implementation to use map and set
> refactor: use es6 structures (map, set) internally

- lib/component.ts
- lib/destroy.ts
- lib/external.ts
- lib/factory.ts
- lib/initialize.ts
- lib/inject.ts
- lib/tsdi.ts
- tests/mock-test.ts
- tsconfig.json
To update the legacy 0.20 version we correct the ts setup.
> chore: update setup

- lib/component.ts
- lib/external.ts
- lib/factory.ts
- lib/global-state.ts
- lib/helper.ts
- lib/inject.ts
- lib/tsdi.ts
- package.json
- tests/cyclic1.ts
- tests/cyclic2.ts
- tests/dependency.ts
- tests/eager1.ts
- tests/eager2.ts
- tests/index-test.ts
- tests/mock-test.ts
- tests/user.ts
- yarn.lock
Configure:
* prettier
* commitlint
* lint-staged
> chore: setup dev tools

- .gitignore
- package.json
- tests/cyclic1.ts
- tests/cyclic2.ts
- tests/dependency.ts
- tests/eager1.ts
- tests/eager2.ts
- tests/index-test.ts
- tests/mock-test.ts
- tests/tsconfig.json
- tests/user.ts
- tsconfig.json
- yarn.lock
Create commonjs, esm and umd versions out of microbundle.
> feat: bundle with microbundle

- .travis.yml
- package.json
- ship.config.js
- yarn.lock
This will ease the release process.
> chore: configure shipjs

- package.json
- yarn.lock
> chore: add shipjs scripts

- .github/workflows/build-and-test.yml
- cypress.json
- package.json
- tests/integration/cypress.ts
- tests/integration/index.spec.ts
- tests/integration/test.umd.html
- tests/integration/tsconfig.json
- tests/integration/umd.ts
- tests/tsconfig.json
- tsconfig.json
- yarn.lock
> feat: add umd test and browser tests

- lib/tsdi.ts
- tests/index-test.ts
This implements lazy factories which created value could then be
injected into components.
> feat: add lazy factory injections

- lib/external.ts
- lib/tsdi.ts
- tests/index-test.ts
- tslint.json
This will wait to call initialize on externals until all injections are
initialized.
> feat: externals could be lazy initialized

- lib/__tests__/index-test.ts
This is a cause of flakyness in the tests.
> test: remove timeout in test condition

- lib/external.ts
> feat: define the external constructor name

- docs/features.md
- lib/__integration__/index.spec.ts
- lib/__tests__/hierarchy-test.ts
- lib/tsdi.ts
> feat: add container hierarchies

- .github/workflows/docs.yml
- website/siteConfig.js
> chore: autoupdate website

- lib/__tests__/on-ready-lifecycle-test.ts
- lib/tsdi.ts
This notifies listeners on ready to be used components
Closes #1121
> feat: add onReady lifecycle
